# 数据模型

+ 数据导入

In [1]:
import pandas as pd
data=pd.read_csv("./HR.csv")
data.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

- 特征工程

In [4]:
data = pd.DataFrame({
    "A":['a0','a1','a1','a2','a3','a4'],
    "B":['b0','b1','b2','b2','b3',None],
    "C":[1,2,None,3,4,5],
    "D":[0.1,10.2,11.4,8.9,9.1,12],
    "E":[10,19,32,25,8,None],
    "F":['f0','f1','g2','f3','f4','a5'],
})

In [5]:
data

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  a5

In [6]:
data.isna()

A      B      C      D      E      F
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False   True  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False   True  False  False   True  False

In [7]:
data.dropna(subset=["B"])

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
2  a1  b2  NaN  11.4  32.0  g2
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

In [16]:
data.A[data.duplicated(["A"])].values

array(['a1'], dtype=object)

In [10]:
data.drop_duplicates(["A"])

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  a5

In [17]:
data.fillna("B*")

A   B   C     D   E   F
0  a0  b0   1   0.1  10  f0
1  a1  b1   2  10.2  19  f1
2  a1  b2  B*  11.4  32  g2
3  a2  b2   3   8.9  25  f3
4  a3  b3   4   9.1   8  f4
5  a4  B*   5  12.0  B*  a5

In [18]:
data.E.interpolate()

0    10.0
1    19.0
2    32.0
3    25.0
4     8.0
5     8.0
Name: E, dtype: float64

In [19]:
upper_q=data.D.quantile(q=0.75)

In [20]:
lower_q=data.D.quantile(q=0.25)

In [21]:
up=upper_q+(upper_q-lower_q)*1.5

In [22]:
low=lower_q-(upper_q-lower_q)*1.5

In [31]:
data[data.D>low][data.D<up]

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


A     B    C     D     E   F
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  a5

In [34]:
data[[True if item.startswith("f") else False for item in list(data.F.values)]]

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

In [17]:
import numpy as np 
import scipy.stats as ss
df = pd.DataFrame({
    "A":ss.norm.rvs(size=10),
    "B":ss.norm.rvs(size=10),
    "C":ss.norm.rvs(size=10),
    "D":np.random.randint(low=0,high=2,size=10)
})

In [34]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
x=df[["A","B","C"]]
x

A         B         C
0  0.033446 -1.110829 -0.461752
1  0.939337  0.021630  0.077212
2  0.547616  0.033719 -0.298177
3 -1.133216 -0.532680 -0.056866
4  1.106623 -1.539717  0.046729
5 -0.894370  1.193031 -0.352754
6 -0.696160  0.450036 -2.057463
7  0.001717  1.110181 -2.043728
8 -0.569869 -0.641535 -0.941834
9  0.501576  0.385332  1.044374

In [21]:
y=df.D

In [24]:
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel
skb=SelectKBest(k=2)
skb.fit(x,y)

SelectKBest(k=2, score_func=<function f_classif at 0x00000000092F8400>)

In [27]:
skb.transform(x)

array([[-1.11082887, -0.4617519 ],
       [ 0.02163049,  0.07721209],
       [ 0.03371909, -0.2981773 ],
       [-0.53267995, -0.05686616],
       [-1.53971747,  0.04672886],
       [ 1.19303139, -0.35275399],
       [ 0.45003643, -2.05746252],
       [ 1.11018094, -2.04372849],
       [-0.64153544, -0.94183439],
       [ 0.38533159,  1.04437409]])

In [28]:
rfe=RFE(estimator=SVR(kernel="linear"),n_features_to_select=2,step=1)

In [31]:
rfe.fit_transform(x,y)

array([[-1.11082887, -0.4617519 ],
       [ 0.02163049,  0.07721209],
       [ 0.03371909, -0.2981773 ],
       [-0.53267995, -0.05686616],
       [-1.53971747,  0.04672886],
       [ 1.19303139, -0.35275399],
       [ 0.45003643, -2.05746252],
       [ 1.11018094, -2.04372849],
       [-0.64153544, -0.94183439],
       [ 0.38533159,  1.04437409]])

In [32]:
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)

In [33]:
sfm.fit_transform(x,y)

array([[-1.11082887, -0.4617519 ],
       [ 0.02163049,  0.07721209],
       [ 0.03371909, -0.2981773 ],
       [-0.53267995, -0.05686616],
       [-1.53971747,  0.04672886],
       [ 1.19303139, -0.35275399],
       [ 0.45003643, -2.05746252],
       [ 1.11018094, -2.04372849],
       [-0.64153544, -0.94183439],
       [ 0.38533159,  1.04437409]])